// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic_client_ext.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterDeviceReq struct {
	AppId                int64    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemVersion        string   `protobuf:"bytes,5,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	SdkVersion           string   `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceReq) Reset()         { *m = RegisterDeviceReq{} }
func (m *RegisterDeviceReq) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceReq) ProtoMessage()    {}
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{0}
}

func (m *RegisterDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceReq.Unmarshal(m, b)
}
func (m *RegisterDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceReq.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceReq.Merge(m, src)
}
func (m *RegisterDeviceReq) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceReq.Size(m)
}
func (m *RegisterDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceReq proto.InternalMessageInfo

func (m *RegisterDeviceReq) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *RegisterDeviceReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegisterDeviceReq) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *RegisterDeviceReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *RegisterDeviceReq) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *RegisterDeviceReq) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

type RegisterDeviceResp struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceResp) Reset()         { *m = RegisterDeviceResp{} }
func (m *RegisterDeviceResp) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceResp) ProtoMessage()    {}
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{1}
}

func (m *RegisterDeviceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceResp.Unmarshal(m, b)
}
func (m *RegisterDeviceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceResp.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceResp.Merge(m, src)
}
func (m *RegisterDeviceResp) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceResp.Size(m)
}
func (m *RegisterDeviceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceResp proto.InternalMessageInfo

func (m *RegisterDeviceResp) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterDeviceReq)(nil), "pb.RegisterDeviceReq")
	proto.RegisterType((*RegisterDeviceResp)(nil), "pb.RegisterDeviceResp")
}

func init() { proto.RegisterFile("logic_client_ext.proto", fileDescriptor_ed5d351b0b933f8f) }

var fileDescriptor_ed5d351b0b933f8f = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xb6, 0x09, 0x76, 0xc4, 0x80, 0x83, 0x2d, 0x8b, 0x1e, 0x0c, 0x05, 0x21, 0xa7,
	0x80, 0xfa, 0x00, 0x1e, 0xd4, 0x43, 0xc1, 0x8b, 0x7b, 0xf0, 0x1a, 0x92, 0xec, 0x50, 0x96, 0xa6,
	0xd9, 0x31, 0xbb, 0x94, 0xf6, 0xb5, 0x7c, 0x42, 0xe9, 0xae, 0x28, 0x6a, 0x6f, 0xfb, 0x7f, 0xfb,
	0x33, 0xfc, 0x7c, 0x30, 0xef, 0xec, 0xca, 0xb4, 0x55, 0xdb, 0x19, 0xea, 0x7d, 0x45, 0x3b, 0x5f,
	0xf2, 0x60, 0xbd, 0xc5, 0x11, 0x37, 0x8b, 0x0f, 0x01, 0xe7, 0x8a, 0x56, 0xc6, 0x79, 0x1a, 0x9e,
	0x68, 0x6b, 0x5a, 0x52, 0xf4, 0x8e, 0x33, 0x48, 0x6b, 0xe6, 0xca, 0x68, 0x29, 0x72, 0x51, 0x8c,
	0x55, 0x52, 0x33, 0x2f, 0x35, 0x22, 0x4c, 0xfc, 0x9e, 0x49, 0x8e, 0x72, 0x51, 0x24, 0x2a, 0xbc,
	0xf1, 0x02, 0x92, 0x66, 0xa8, 0x7b, 0x2d, 0xc7, 0xb9, 0x28, 0xa6, 0x2a, 0x86, 0x03, 0xdd, 0x58,
	0x4d, 0x9d, 0x9c, 0x44, 0x1a, 0x02, 0xde, 0x40, 0xe6, 0xf6, 0xce, 0xd3, 0xa6, 0xda, 0xd2, 0xe0,
	0x8c, 0xed, 0x65, 0x12, 0xbe, 0xcf, 0x22, 0x7d, 0x8b, 0x10, 0xaf, 0xe1, 0xd4, 0xe9, 0xf5, 0x77,
	0x27, 0x0d, 0x1d, 0x70, 0x7a, 0xfd, 0x55, 0x58, 0xdc, 0x02, 0xfe, 0xdd, 0xec, 0x18, 0xaf, 0x60,
	0xaa, 0x43, 0xfa, 0xd9, 0x7d, 0x12, 0xc1, 0x52, 0xdf, 0xbd, 0x42, 0xf6, 0x72, 0xb0, 0xf0, 0x18,
	0x24, 0x3c, 0xef, 0x3c, 0x3e, 0x40, 0xf6, 0xfb, 0x08, 0xce, 0x4a, 0x6e, 0xca, 0x7f, 0x32, 0x2e,
	0xe7, 0xc7, 0xb0, 0xe3, 0x26, 0x0d, 0x16, 0xef, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x34, 0xa4,
	0xdd, 0xfc, 0x5f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogicClientExtClient is the client API for LogicClientExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicClientExtClient interface {
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
}

type logicClientExtClient struct {
	cc *grpc.ClientConn
}

func NewLogicClientExtClient(cc *grpc.ClientConn) LogicClientExtClient {
	return &logicClientExtClient{cc}
}

func (c *logicClientExtClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, "/pb.LogicClientExt/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicClientExtServer is the server API for LogicClientExt service.
type LogicClientExtServer interface {
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
}

// UnimplementedLogicClientExtServer can be embedded to have forward compatible implementations.
type UnimplementedLogicClientExtServer struct {
}

func (*UnimplementedLogicClientExtServer) RegisterDevice(ctx context.Context, req *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}

func RegisterLogicClientExtServer(s *grpc.Server, srv LogicClientExtServer) {
	s.RegisterService(&_LogicClientExt_serviceDesc, srv)
}

func _LogicClientExt_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicClientExtServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicClientExt/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicClientExtServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicClientExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogicClientExt",
	HandlerType: (*LogicClientExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _LogicClientExt_RegisterDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic_client_ext.proto",
}
