// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic_client_ext.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 注册一个设备
type RegisterDeviceReq struct {
	AppId                int64    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SystemVersion        string   `protobuf:"bytes,5,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	SdkVersion           string   `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceReq) Reset()         { *m = RegisterDeviceReq{} }
func (m *RegisterDeviceReq) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceReq) ProtoMessage()    {}
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{0}
}

func (m *RegisterDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceReq.Unmarshal(m, b)
}
func (m *RegisterDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceReq.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceReq.Merge(m, src)
}
func (m *RegisterDeviceReq) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceReq.Size(m)
}
func (m *RegisterDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceReq proto.InternalMessageInfo

func (m *RegisterDeviceReq) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *RegisterDeviceReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegisterDeviceReq) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *RegisterDeviceReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *RegisterDeviceReq) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *RegisterDeviceReq) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

// 添加一个用户
type User struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nicknamec            string   `protobuf:"bytes,2,opt,name=nicknamec,proto3" json:"nicknamec,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Extra                string   `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetNicknamec() string {
	if m != nil {
		return m.Nicknamec
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type AddUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{2}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AddUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResp) Reset()         { *m = AddUserResp{} }
func (m *AddUserResp) String() string { return proto.CompactTextString(m) }
func (*AddUserResp) ProtoMessage()    {}
func (*AddUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{3}
}

func (m *AddUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResp.Unmarshal(m, b)
}
func (m *AddUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResp.Marshal(b, m, deterministic)
}
func (m *AddUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResp.Merge(m, src)
}
func (m *AddUserResp) XXX_Size() int {
	return xxx_messageInfo_AddUserResp.Size(m)
}
func (m *AddUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResp proto.InternalMessageInfo

// 获得用户
type GetUserReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{4}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResp) Reset()         { *m = GetUserResp{} }
func (m *GetUserResp) String() string { return proto.CompactTextString(m) }
func (*GetUserResp) ProtoMessage()    {}
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{5}
}

func (m *GetUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp.Unmarshal(m, b)
}
func (m *GetUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp.Marshal(b, m, deterministic)
}
func (m *GetUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp.Merge(m, src)
}
func (m *GetUserResp) XXX_Size() int {
	return xxx_messageInfo_GetUserResp.Size(m)
}
func (m *GetUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp proto.InternalMessageInfo

func (m *GetUserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterDeviceResp struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceResp) Reset()         { *m = RegisterDeviceResp{} }
func (m *RegisterDeviceResp) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceResp) ProtoMessage()    {}
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed5d351b0b933f8f, []int{6}
}

func (m *RegisterDeviceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceResp.Unmarshal(m, b)
}
func (m *RegisterDeviceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceResp.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceResp.Merge(m, src)
}
func (m *RegisterDeviceResp) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceResp.Size(m)
}
func (m *RegisterDeviceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceResp proto.InternalMessageInfo

func (m *RegisterDeviceResp) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterDeviceReq)(nil), "pb.RegisterDeviceReq")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*AddUserReq)(nil), "pb.AddUserReq")
	proto.RegisterType((*AddUserResp)(nil), "pb.AddUserResp")
	proto.RegisterType((*GetUserReq)(nil), "pb.GetUserReq")
	proto.RegisterType((*GetUserResp)(nil), "pb.GetUserResp")
	proto.RegisterType((*RegisterDeviceResp)(nil), "pb.RegisterDeviceResp")
}

func init() { proto.RegisterFile("logic_client_ext.proto", fileDescriptor_ed5d351b0b933f8f) }

var fileDescriptor_ed5d351b0b933f8f = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0x71, 0x13, 0x27, 0xf5, 0x09, 0xcd, 0xb6, 0xc3, 0xda, 0x99, 0xae, 0x63, 0xc1, 0x50,
	0x08, 0x1d, 0x04, 0xd6, 0x3d, 0xc0, 0x18, 0xdb, 0x18, 0x81, 0x5d, 0x89, 0x75, 0xb7, 0x46, 0xb1,
	0x0e, 0x45, 0xc4, 0x7f, 0x34, 0x49, 0x09, 0xee, 0x23, 0xed, 0x76, 0x0f, 0xb1, 0xe7, 0x1a, 0x92,
	0x5c, 0x7b, 0xd9, 0x1f, 0x7a, 0xe7, 0xef, 0xd3, 0xcf, 0xd2, 0xf7, 0x1d, 0x0e, 0x9c, 0x95, 0xcd,
	0xad, 0x2c, 0xf2, 0xa2, 0x94, 0x54, 0xdb, 0x9c, 0x5a, 0xbb, 0x52, 0xba, 0xb1, 0x0d, 0x1e, 0xa9,
	0x4d, 0xf6, 0x23, 0x82, 0x27, 0x8c, 0x6e, 0xa5, 0xb1, 0xa4, 0x3f, 0xd0, 0x5e, 0x16, 0xc4, 0xe8,
	0x1b, 0x9e, 0xc2, 0x84, 0x2b, 0x95, 0x4b, 0x91, 0x46, 0x8b, 0x68, 0x39, 0x62, 0x31, 0x57, 0x6a,
	0x2d, 0x10, 0x61, 0x6c, 0xef, 0x14, 0xa5, 0x47, 0x8b, 0x68, 0x19, 0x33, 0xff, 0x8d, 0x4f, 0x21,
	0xde, 0x68, 0x5e, 0x8b, 0x74, 0xb4, 0x88, 0x96, 0x09, 0x0b, 0xc2, 0xb9, 0x55, 0x23, 0xa8, 0x4c,
	0xc7, 0xc1, 0xf5, 0x02, 0x2f, 0x61, 0x6e, 0xee, 0x8c, 0xa5, 0x2a, 0xdf, 0x93, 0x36, 0xb2, 0xa9,
	0xd3, 0xd8, 0x1f, 0x9f, 0x04, 0xf7, 0x6b, 0x30, 0xf1, 0x25, 0xcc, 0x8c, 0xd8, 0xf6, 0xcc, 0xc4,
	0x33, 0x60, 0xc4, 0xb6, 0x03, 0xb2, 0x9f, 0x11, 0x8c, 0x6f, 0x0c, 0x69, 0x7c, 0x06, 0xd3, 0x9d,
	0x21, 0x3d, 0x04, 0x9d, 0x38, 0xb9, 0x16, 0x78, 0x01, 0x49, 0x2d, 0x8b, 0x6d, 0xcd, 0x2b, 0x2a,
	0x7c, 0xdc, 0x84, 0x0d, 0x06, 0x3e, 0x86, 0x91, 0xa1, 0xd6, 0x27, 0x8e, 0x99, 0xfb, 0xc4, 0x17,
	0x00, 0x7c, 0xcf, 0x2d, 0xd7, 0xf9, 0x4e, 0xdf, 0x87, 0x4e, 0x82, 0x73, 0xa3, 0x4b, 0x57, 0x87,
	0x5a, 0xab, 0x79, 0x97, 0x37, 0x08, 0x97, 0xb3, 0xd0, 0xc4, 0x2d, 0xe5, 0x56, 0x56, 0xe4, 0x73,
	0x8e, 0x18, 0x04, 0xeb, 0x8b, 0xac, 0xc8, 0x01, 0x3b, 0x25, 0x7a, 0x60, 0x1a, 0x80, 0x60, 0x39,
	0x20, 0xbb, 0x02, 0x78, 0x27, 0x84, 0xab, 0xe2, 0xa6, 0x7e, 0x01, 0x63, 0x17, 0xdf, 0x57, 0x99,
	0x5d, 0x1f, 0xaf, 0xd4, 0x66, 0xe5, 0x8f, 0xbc, 0x9b, 0x9d, 0xc0, 0xac, 0x67, 0x8d, 0xca, 0x2e,
	0x01, 0x3e, 0x91, 0xbd, 0xff, 0xf5, 0x7f, 0x83, 0xc8, 0x5e, 0xc1, 0xac, 0xc7, 0x8c, 0x7a, 0xe0,
	0x89, 0xd7, 0x80, 0x7f, 0xee, 0x82, 0x51, 0xf8, 0x1c, 0x12, 0xe1, 0xd5, 0x70, 0xfb, 0x71, 0x30,
	0xd6, 0xe2, 0xfa, 0x7b, 0x04, 0xf3, 0xcf, 0x6e, 0xbd, 0xde, 0xfb, 0xed, 0xfa, 0xd8, 0x5a, 0x7c,
	0x0b, 0xf3, 0xc3, 0x5b, 0xf0, 0xd4, 0xbd, 0xf3, 0xd7, 0x96, 0x9d, 0x9f, 0xfd, 0xcb, 0x36, 0x0a,
	0xaf, 0x60, 0xda, 0x35, 0xc5, 0xb9, 0x43, 0x86, 0x11, 0x9d, 0x3f, 0x3a, 0xd0, 0x81, 0xed, 0xfa,
	0x05, 0x76, 0x98, 0x49, 0x60, 0x7f, 0x2b, 0xbf, 0x99, 0xf8, 0xb5, 0x7f, 0xf3, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0xd4, 0x74, 0xd1, 0xf7, 0x10, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogicClientExtClient is the client API for LogicClientExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicClientExtClient interface {
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
	//添加用户信息
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error)
	// 获取用户信息
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
}

type logicClientExtClient struct {
	cc *grpc.ClientConn
}

func NewLogicClientExtClient(cc *grpc.ClientConn) LogicClientExtClient {
	return &logicClientExtClient{cc}
}

func (c *logicClientExtClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, "/pb.LogicClientExt/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClientExtClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	out := new(AddUserResp)
	err := c.cc.Invoke(ctx, "/pb.LogicClientExt/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClientExtClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	out := new(GetUserResp)
	err := c.cc.Invoke(ctx, "/pb.LogicClientExt/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicClientExtServer is the server API for LogicClientExt service.
type LogicClientExtServer interface {
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
	//添加用户信息
	AddUser(context.Context, *AddUserReq) (*AddUserResp, error)
	// 获取用户信息
	GetUser(context.Context, *GetUserReq) (*GetUserResp, error)
}

// UnimplementedLogicClientExtServer can be embedded to have forward compatible implementations.
type UnimplementedLogicClientExtServer struct {
}

func (*UnimplementedLogicClientExtServer) RegisterDevice(ctx context.Context, req *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (*UnimplementedLogicClientExtServer) AddUser(ctx context.Context, req *AddUserReq) (*AddUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedLogicClientExtServer) GetUser(ctx context.Context, req *GetUserReq) (*GetUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterLogicClientExtServer(s *grpc.Server, srv LogicClientExtServer) {
	s.RegisterService(&_LogicClientExt_serviceDesc, srv)
}

func _LogicClientExt_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicClientExtServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicClientExt/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicClientExtServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicClientExt_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicClientExtServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicClientExt/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicClientExtServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicClientExt_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicClientExtServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LogicClientExt/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicClientExtServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicClientExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogicClientExt",
	HandlerType: (*LogicClientExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _LogicClientExt_RegisterDevice_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _LogicClientExt_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _LogicClientExt_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic_client_ext.proto",
}
